= CspaceConfigUntangler

== Conceptual overview
Reads JSON config file. 

Gets field definitions (`field_defs`), including repeatability, data type, value source, XML field name and parents, etc.

Gets fields as defined for use in forms (`form_fields`), including the panel in which the field is included, and UI hierarchy.

Gets messages assigned to fields, panels, and input tables from field_defs and the messages hash under the profile and record types. *It is assumed messages set at profile level will override those at lower levels*

For a given profile, matches each form_field to its corresponding field_def and creates a `field` object that combines all info for the field. If a form_field represents a field group populated with structured date fields, the individual structured date fields are provided from the extension, and the original form_field is treated as the parent UI grouping.

_Note: there may be field_defs in a profile which do not match any form_fields. Field objects are not created/reported for these, because if a field has not been made available for viewing/editing in a form, it is not considered included in the profile._

== JSON config source files
Since there is no way to programmatically grab the JSON config, this currently requires you to manually download the JSON config files from the following links. The JSON files should be saved with the as `{profilename}.json` in the `data/configs/{version}` directory:

-  https://core.collectionspace.org/cspace/core/config
-  https://anthro.collectionspace.org/cspace/anthro/config
-  https://fcart.collectionspace.org/cspace/fcart/config
-  https://lhmc.collectionspace.org/cspace/lhmc/config
-  https://publicart.collectionspace.org/cspace/publicart/config
-  https://materials.collectionspace.org/cspace/materials/config
-  https://herbarium.collectionspace.org/cspace/herbarium/config (not applied? - dev is)
-  https://botgarden.collectionspace.org/cspace/botgarden/config (not applied?)
-  https://bonsai.collectionspace.org/cspace/bonsai/config
-  https://cspace.ohiohistory.org/cspace/ohc/config


If you need to add another config to the handling, edit the `CDC.const_set('PROFILES')` value in `lib/command_line.rb`.

== Usage

* Clone this repo
* `cd` into cloned directory
* `bundle/install`
* Download your configs into the appropriate `data/configs/{version}` directory or directories
* Configure your constants https://github.com/lyrasis/cspace-config-untangler/blob/7dbf54bc5f6f8df4079aa9de8b4f8666af4b1fd8/lib/cspace_config_untangler.rb#L17-L19[here]
** CONFIGDIR should point to the directory for the default version of the configs you want to work with. A forthcoming command line function to allow the comparison of two versions of the same profile will allow you to specify what to compare your default version against.
* Set up `profile_config.yaml`. See sub-section below for details on this.

Once this is done, from the cloned directory, you should be able to type `exe/ccu` (or just `ccu` depending on your setup) at the command prompt to get the list of available functions with their brief descriptions.

`main_profile`, `all_profiles`, and `check_profiles` help you verify your config and use of the --profiles option are ok.

`readable_profiles` saves the specified JSON config(s) to new files as pretty-printed JSON you can meaningfully grep or deal with in Oxygen or other editors.

`list_rec_types` and `extensions_by_profile` give some high-level info for each profile.

`fields_csv` outputs CSV file of combined data from field_defs and form_fields for each profile indicated.

===`profile_config.yaml` setup

This YAML config supports using the CSpace services REST API to get the vocabularies used by a profile.

It is parsed and used by `/lib/cspace_config_untangler/site_config.rb`.

Use the following format:

[source, yaml]
----
profiles:
  core:
    setup: 'standard'
  anthro:
    setup: 'standard'
  clientname:
    prod:
      base: 'cspace.clientdomain.org'
      user: 'admin@cspace.clientdomain.org'
      pw: 'passwordstring'
    dev:
      base: 'client.lyrtech.org'
      user: 'admin@cspace.clientdomain.org'
      pw: 'passwordstring'
----

The behavior of `setup: standard` for authenticating to demo or dev is hard-coded for LYRASIS-hosting assumptions in `site_config.rb`.

For different authentication patterns, follow the pattern shown for the `clientname` profile. `clientname` must match a profile listed in your constants. Setting up `prod` is required. Setting up `dev` is optional.


== Known limitations/issues

- For 5.2 configs, data source values are not consistently supplied for structured date fields. This is because configuration of the structured date fields was not written out to the JSON config in a standard way until 6.0.
- Does not currently report on fields in the `ns2:collectionspace_core` namespace 
- Does not currently report on fields in the `rel:relations-common-list` namespace because the way this data is defined in the config is very different from the rest
