= CspaceConfigUntangler

== Conceptual overview
Reads JSON config file output by CollectionSpace application. 

Gets field definitions (`field_defs`), including repeatability, data type, value source, XML field name and parents, etc.

Gets fields as defined for use in forms (`form_fields`), including the panel in which the field is included, and UI hierarchy.

Gets messages assigned to fields, panels, and input tables from field_defs and the messages hash under the profile and record types. *It is assumed messages set at profile level will override those at lower levels*

For a given profile, matches each form_field to its corresponding field_def and creates a `field` object that combines all info for the field. If a form_field represents a field group populated with structured date fields, the individual structured date fields are provided from the extension, and the original form_field is treated as the parent UI grouping.

_Note: there may be field_defs in a profile which do not match any form_fields. Field objects are not created/reported for these, because if a field has not been made available for viewing/editing in a form, it is not considered included in the profile._

== JSON config source files
Since there is no way to programmatically grab the JSON config, this currently requires you to manually download the JSON config files from the following links. The JSON files should be saved with the as `{profilename}.json` in the `data/configs` directory:

-  https://core.collectionspace.org/cspace/core/config
-  https://anthro.collectionspace.org/cspace/anthro/config
-  https://fcart.collectionspace.org/cspace/fcart/config
-  https://lhmc.collectionspace.org/cspace/lhmc/config
-  https://publicart.collectionspace.org/cspace/publicart/config
-  https://materials.collectionspace.org/cspace/materials/config
-  https://herbarium.collectionspace.org/cspace/herbarium/config
-  https://botgarden.collectionspace.org/cspace/botgarden/config
-  https://bonsai.collectionspace.org/cspace/bonsai/config

And for the latest dev versions of profiles:

-  https://core.dev.collectionspace.org/cspace/core/config
-  https://anthro.dev.collectionspace.org/cspace/anthro/config
-  https://fcart.dev.collectionspace.org/cspace/fcart/config
-  https://lhmc.dev.collectionspace.org/cspace/lhmc/config
-  https://publicart.dev.collectionspace.org/cspace/publicart/config
-  https://materials.dev.collectionspace.org/cspace/materials/config
-  https://herbarium.dev.collectionspace.org/cspace/herbarium/config
-  https://botgarden.dev.collectionspace.org/cspace/botgarden/config 
-  https://bonsai.dev.collectionspace.org/cspace/bonsai/config


Set `CCU.const_set('MAINPROFILE')` value in `lib/cspace_config_untangler.rb`.

== Setup

* Tested with Ruby 2.7.0
* Do `bundle --version`
- If the version of Bundler is lower than 2.1.2, do `gem update bundler`
** Bundler should come standard with Ruby 2.7.0, but may be an older version. If you get an error that you don't have Bundler installed when you try to check the version, do `gem install bundler`
* Clone this repo
* `cd` into cloned directory
* `bundle/install`
* Download your configs into the appropriate `data/configs` directory or directories
* Configure your constants https://github.com/collectionspace/cspace-config-untangler/blob/master/lib/cspace_config_untangler.rb[in `lib/cspace_config_untangler.rb`]
* Rename `data/profile_config_example.yaml` to  `data/profile_config.yaml` and set up any custom configs you want to use following the pattern given. See sub-section below for details on this.

=== `profile_config.yaml` setup

This YAML config supports using the CSpace services REST API to get the vocabularies used by a profile.

It is parsed and used by `/lib/cspace_config_untangler/site_config.rb`.

Use the following format:

[source, yaml]
----
profiles:
  core:
    setup: 'standard'
  anthro:
    setup: 'standard'
  bonsai:
   setup: 'standard'
  noncommunity_profile_name:
    prod:
      base: 'cspace.clientdomain.org'
      user: 'admin@cspace.clientdomain.org'
      pw: 'passwordstring'
    dev:
      base: 'client.lyrtech.org'
      user: 'admin@cspace.clientdomain.org'
      pw: 'passwordstring'
----

==== To use community profiles

The behavior of `setup: standard` for authenticating to demo or dev is hard-coded for LYRASIS-hosting assumptions in `site_config.rb`. (These authorization credentials are stated on the public landing pages for the demo and dev instances, so this is not secure info, but will eventually be refactored out.

*All you need to do is add the community profile name you want to use, and `setup: 'standard'`.*

==== To use custom profiles/configs

For different authentication patterns, follow the pattern shown for the `noncommunity_profile_name` profile.

The profile name must match a JSON config file name for a profile in your `CONFIGDIR` directory, without any version suffixing. For instance, you may have the following in `CONFIGDIR`:

- noncommunity_profile_name_1_0_0
- noncommunity_profile_name_1_0_1

The name in your YAML config should be as shown above. The `lib/cspace_config_untangler/site_config.rb` code handles matching the specific profile version with the correct authentication.

If you need to authenticate differently for different versions, control this by renaming the relevant JSON config file, and adding an entry for that name in the YAML.

Setting up `prod` is required. Setting up `dev` is optional.

== Usage

Once the setup is done, from the cloned directory, you should be able to type `exe/ccu` (or just `ccu` depending on your setup) at the command prompt to get the list of available functions with their brief descriptions.

*The best source of info on what each function does and how to use it is the `exe/ccu` command (overview) and `exe/ccu help {function_name}` (for details on options and implementation).*

`main_profile`, `all_profiles`, and `check_profiles` help you verify your config and use of the --profiles option are ok.

`readable_profiles` saves the specified JSON config(s) to new files as pretty-printed JSON you can meaningfully grep or deal with in Oxygen or other editors.

`list_rec_types` and `extensions_by_profile` give some high-level info for each profile.

`fields_csv` outputs CSV file of combined data from field_defs and form_fields for each profile indicated.



== Known limitations/issues

- For 5.2 configs, data source values are not consistently supplied for structured date fields. This is because configuration of the structured date fields was not written out to the JSON config in a standard way until 6.0.
- Does not currently report on fields in the `ns2:collectionspace_core` namespace 
- Does not currently report on fields in the `rel:relations-common-list` namespace because the way this data is defined in the config is very different from the rest
- `contact` and `blob` get reported/treated as extensions within the tool, rather than sub-records
