= CspaceConfigUntangler

== Conceptual overview
Reads JSON config file output by CollectionSpace application. 

Gets field definitions (`field_defs`), including repeatability, data type, value source, XML field name and parents, etc.

Gets fields as defined for use in forms (`form_fields`), including the panel in which the field is included, and UI hierarchy.

Gets messages assigned to fields, panels, and input tables from field_defs and the messages hash under the profile and record types. *It is assumed messages set at profile level will override those at lower levels*

For a given profile, matches each form_field to its corresponding field_def and creates a `field` object that combines all info for the field. If a form_field represents a field group populated with structured date fields, the individual structured date fields are provided from the extension, and the original form_field is treated as the parent UI grouping.

_Note: there may be field_defs in a profile which do not match any form_fields. Field objects are not created/reported for these, because if a field has not been made available for viewing/editing in a form, it is not considered included in the profile._

== JSON config source files
Since there is no way to programmatically grab the JSON config, this currently requires you to manually download the JSON config files from the following links. The JSON files should be saved as `{profilename}.json` in the `data/configs` directory.

IMPORTANT: You must follow the config naming conventions specified below in order for the Untangler to properly identify profile name and version!

-  https://core.collectionspace.org/cspace/core/config
-  https://anthro.collectionspace.org/cspace/anthro/config
-  https://bonsai.collectionspace.org/cspace/bonsai/config
-  https://botgarden.collectionspace.org/cspace/botgarden/config
-  https://fcart.collectionspace.org/cspace/fcart/config
-  https://herbarium.collectionspace.org/cspace/herbarium/config
-  https://lhmc.collectionspace.org/cspace/lhmc/config
-  https://materials.collectionspace.org/cspace/materials/config
-  https://publicart.collectionspace.org/cspace/publicart/config

And for the latest dev versions of profiles:

-  https://core.dev.collectionspace.org/cspace/core/config
-  https://anthro.dev.collectionspace.org/cspace/anthro/config
-  https://fcart.dev.collectionspace.org/cspace/fcart/config
-  https://lhmc.dev.collectionspace.org/cspace/lhmc/config
-  https://publicart.dev.collectionspace.org/cspace/publicart/config
-  https://materials.dev.collectionspace.org/cspace/materials/config
-  https://herbarium.dev.collectionspace.org/cspace/herbarium/config
-  https://botgarden.dev.collectionspace.org/cspace/botgarden/config 
-  https://bonsai.dev.collectionspace.org/cspace/bonsai/config


Set `CCU.const_set('MAINPROFILE')` value in `lib/cspace_config_untangler.rb`.

=== Config (and resulting mapper/template) naming conventions

Config file name must contain the profile name and profile version.

Use `_` (underscore) to separate the profile name and profile version sections of the name.

Use `-` (hyphen) to separate words/numbers within a section.

Examples:

`anthro_4-1-2.json`

`my-custom-config_2-0.json`

This allows the Untangler to split the config file name on `_` and unambiguously determine profile name vs. profile version.

Output files follow the same convention, adding the recordtype section:

`anthro_4-1-2_concept-associated.json`

== Setup

* Tested with Ruby 2.7.0
* Do `bundle --version`
- If the version of Bundler is lower than 2.1.2, do `gem update bundler`
** Bundler should come standard with Ruby 2.7.0, but may be an older version. If you get an error that you don't have Bundler installed when you try to check the version, do `gem install bundler`
* Clone this repo
* `cd` into cloned directory
* `bundle/install`
* Download your configs into the appropriate `data/configs` directory or directories
* Configure your constants https://github.com/collectionspace/cspace-config-untangler/blob/master/lib/cspace_config_untangler.rb[in `lib/cspace_config_untangler.rb`]

== Usage

Once the setup is done, from the cloned directory, you should be able to type `exe/ccu` (or just `ccu` depending on your setup) at the command prompt to get the list of available functions with their brief descriptions.

*The best source of info on what each function does and how to use it is the `exe/ccu` command (overview) and `exe/ccu help {function_name}` (for details on options and implementation).*

There are some instructions for common tasks in the `doc` directory.

`main_profile`, `all_profiles`, and `check_profiles` help you verify your config and use of the --profiles option are ok.

`readable_profiles` saves the specified JSON config(s) to new files as pretty-printed JSON you can meaningfully grep or deal with in Oxygen or other editors.

`list_rec_types` and `extensions_by_profile` give some high-level info for each profile.

`fields_csv` outputs CSV file of combined data from field_defs and form_fields for each profile indicated.



== Known limitations/issues

=== General

IMPORTANT: This tool can only be used confidently with configs from CollectionSpace 6.1 and newer

- For 5.2 configs, data source values are not consistently supplied for structured date fields. This is because configuration of the structured date fields was not written out to the JSON config in a standard way until 6.0.
- The 6.1 release further refined the JSON config output allowing the full functionality of this tool
- Does not currently report on fields in the `ns2:collectionspace_core` namespace 
- Does not currently report on fields in the `rel:relations-common-list` namespace because the way this data is defined in the config is very different from the rest
- `contact` and `blob` get reported/treated as extensions within the tool, rather than sub-records

=== Working with non-community profiles

* Do `exe/ccu write_fields_csv -p all` and check whether the `data_type` column has any blank values. If so, probably your profile has configured some fields from extensions in an unexpected manner. This can cause `forms/default/props/subpath` values (used to create form_field ids) to not match the `fields/document/.../{fieldname}/[config]/messages/name/id` values (used to create field_def ids) for some fields. The Untangler is then unable to match up form_field info with field_def info to generate the necessary combined field info required for fully-populated fields CSV, CSV template, and RecordMapper output. You'll need to do some hard-coding somewhere in the code to get a match
* Do you have fields with the same name in different namespaces in the same record type? Use `exe/ccu fields nonunique` to generate a listing of any such fields.
** The code tries to automatically fix this https://github.com/collectionspace/cspace-config-untangler/blob/16a3da1dec21a80e7658d065d85a3cc548c72292/lib/cspace_config_untangler/record_types.rb#L77-L81[here] but if any non-unique field names are sneaking through, you may need to hard-code something to fix this. Otherwise, you will get two columns in your CSV template with the same header and it won't be clear which field that data should be imported into.
* If you have record types with (a) *no* required field; or (b) multiple required fields, you will need to hard-code `identifier_field` values in `record_mapper.rb`'s `get_id_field` method.
* If you have created any form templates that include fields that are *not* included in your `default` template, your Untangler output will not include those fields. The assumption is that the `default` form contains all possible fields for a record type. 
* If you are using CollectionSpace 6.1 and are round-tripping exported data back in using the CollectionSpace CSV Importer, you will need to add your profile name(s) and version(s) to the LAST_FANCY_VERSION constant of the ColumnNameStylable mixin module.
** This will ensure you get CSV template column headers (and column names in your record mappers) that are closer to what your CollectionSpace application outputs when search results are exported. There were some bugs in how column headers were exported in 6.1 and some mismatches between what 6.1 produced and what the Untangler produced.
** Starting with CS 7.0, the export and import columns should be consistent going forward.
