= Generating mappers and mapper manifest

mapper:: Instructions/data needed in order to convert flat data into CSpace XML, in a structured JSON document. Each record type in a profile has its own mapper. The `collectionspace-mapper` application calls these ``RecordMapper``s.
mapper manifest:: A list of available mappers for use in configuring `cspace-batch-import`.

The following instructions assume:

- you want to generate mappers and a mapper manifest for all record types in the current versions of all community profiles; and
- the current configs for the community profiles are in your `data/configs` directory

== Create the mappers
This will create mappers for each profile in a separate subdirectory of `data/mappers/release_#`:

`exe/ccu mappers write -p all -o data/mappers/release_# -s y`

For details on the options:

`exe/ccu mappers help write`

== Validate the newly created mappers

See the description under `exe/ccu mappers help validate` for what this checks.

The following will recursively validate (in all the subdirectories) all the mappers created in the previous step.

`exe/ccu mappers validate -i data/mappers/release_#`

== Create the mapper manifest

The following will create a manifest listing all *valid* mappers created above:

`exe/ccu mappers manifest -i release_# -o data/mapper_manifests/community_profile_mappers_release_#.json`

To create a dev manifest:

 `exe/ccu mappers manifest -i release_{release#} -o data/mapper_manifests/dev_mappers_{release#}.json -d true`

The dev manifest is a subset of the full manifest, containing only a few mappers for use in dev/testing. To change which profile/record types are included in a dev manifest, edit the `DEV_MAPPERS` constant in `lib/cspace-config-untangler/manifest_dev.rb`
